
services:
  calculator: 
    build: .
    image: cowsay_op
    container_name: cowCalculator
    ports:
    - "1000:1000"
    environment:
    - PORT=1000
    volumes:
    - .:/app
    command:
      npx nodemon backend/src/index.js